### ISSUE TITLE
Error on Deleting a page in Trash

### ISSUE THREAD

**Issue by matjazpotocnik** [thetuningspoon/AdminPreSaveValidation#1]
When page is in Trash and you edit that page, then go to Delete tab and click on Delete Permanently button, the error is shown as e.originalEvent is undefined.

![image](https://user-images.githubusercontent.com/7663992/233165793-ff022cb3-31ad-4b90-b96d-921951274b6d.png)

**Comment by thetuningspoon** [comment]
Thanks for the report. I will take a look at this as soon as I get a chance.

**Comment by thetuningspoon** [comment]
Fixed in 1.1.2
